ci: add hard exit path

diff --git a/.github/workflows/cpp-linter.yml b/.github/workflows/cpp-linter.yml
--- a/.github/workflows/cpp-linter.yml
+++ b/.github/workflows/cpp-linter.yml
@@ -37,4 +37,4 @@ jobs:
       - name: Check Result
         if: steps.linter.outputs.checks-failed > 0
         run: |
-          echo "Failed linting."
+          echo "Failed linting." && exit 1
